[theme]
base = "light"
primaryColor = "#003a6b"         
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6fa"
textColor = "#1a1a1a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
runOnSave = true
